---
title: "3flye1m_KM"
author: "Kimia Mansouri"
format: html
editor: visual
---

# **Course 3, Day 2: Functional Genomics**

## **Load Libraries**

```{r}
#| eval: false
#Loop that checks if the packages GO.db and AnnotationDbi are already installed
#If not, install them

p_check <- c("GO.db", "AnnotationDbi")

for(i in seq_along(p_check)){
  
  if(p_check[i] %in% installed.packages()[,"Package"]){
    print(paste("Package",p_check[i], "is already installed", sep = " "))
  }else{
    print(paste("installing package", p_check[i], sep = " ")) 
    BiocManager::install(p_check[i], force = TRUE)
  }
}

#Install the ggVennDiagram package
install.packages("ggVennDiagram")
```

```{r}
#| echo: false
#| warning: false
#| message: false
#Load packages
library("tidyverse")
library("Gviz")
library("GenomicFeatures")
library("rtracklayer")
library("Biostrings")
library("GO.db")
library("AnnotationDbi")
library("ggVennDiagram")
```

## **Phase 2: Structural Visualization (Zooming In)**

### **1. Identifying the Largest Contigs**

```{r}

gff_path <- "data/data_kimia/Saccharomyces_cerevisiae.gff3"

txdb_demo <- makeTxDbFromGFF(gff_path, format = "gff3")

lns <- seqlengths(txdb_demo)
txdb_demo

names(lns)[which.max(lns)]

biostring_assembly <- Biostrings::readDNAStringSet("data/data_kimia/Myles_consensus.fasta")
which(width(biostring_assembly)==max(width(biostring_assembly)))
biostring_assembly[231]

which(seqlevels(txdb_demo)=="scaffold_20")
seqlevels(txdb_demo)

options(ucscChromosomeNames=FALSE)

s.c_track <- GeneRegionTrack(txdb_demo, 
                             chromosome = seqlevels(txdb_demo)[113],
                             name = "Predicted Genes",
                             transcriptAnnotation = "gene",
                             background.title = "darkgreen")

axis_track <- GenomeAxisTrack()

scaffold_20_plot <- plotTracks(list(axis_track, s.c_track),
           from = 1, 
           to = 45000,
           chromosome = seqlevels(txdb_demo)[113],
           main = "Funannotate Predictions: Scaffold 20")

scaffold_20_plot

```

## **Phase 3: Integrating Function (The Overlay)**

```{r}
annotations_eggnog_km <- readxl::read_excel("data/data_kimia/3scaff1med.emapper.annotations.xlsx", skip = 2)

GRanges_gff <- import.gff("data/data_kimia/Saccharomyces_cerevisiae.gff3")

match_gff_eggnog <- match(GRanges_gff$ID, annotations_eggnog_km$query)

GRanges_gff$symbol <- annotations_eggnog_km$Preferred_name[match_gff_eggnog]

GRanges_gff$symbol


options(ucscChromosomeNames=FALSE)
fung_track <- GeneRegionTrack(GRanges_gff, 
                             chromosome = seqlevels(GRanges_gff)[113],
                             name = "Predicted Genes",
                             transcriptAnnotation = "symbol",
                             background.title = "darkgreen")
axis_track <- GenomeAxisTrack()

plot_matches <- plotTracks(list(axis_track, fung_track),
           from = 1, 
           to = 45000,
           chromosome = seqlevels(GRanges_gff)[113],
           main = "Funannotate Predictions: Matches")
```

**Assignment Question 2:** Component of the TREX complex required for nuclear mRNA export;

## **Phase 4: Global Functional Summary (Zooming Out)**

```{r}
separated_GO <- annotations_eggnog_km %>%
  separate_rows(GOs, sep = ",")

GO_TERMS <- AnnotationDbi::select(GO.db,
                                      keys =unique(separated_GO$GOs),
                                      columns = c("TERM"),
                                      keytype = "GOID")

separated_GO <- left_join(separated_GO,GO_TERMS, by= c("GOs" = "GOID"))

top_ten <- separated_GO %>%
  count(TERM, sort = TRUE) %>%
  filter(!is.na(TERM)) %>% 
  slice_head(n=10)
```

```{r}
#| warning: false
#| message: false
library(ggplot2)
library(forcats)

 ggplot(top_ten, aes(x = fct_reorder(TERM, n), y = n)) + 
  geom_bar(stat = "identity") + 
  coord_flip() + # Makes long labels readable
  labs(x = "GO Term", y = "Count")

```

## **Phase 5: Comparative Analysis (The Deep Dive)**

```{r}
# Example search terms: "glycolysis", "fermentation"
pathway_hits <- annotations_eggnog_km %>%
  filter(str_detect(Description, regex("alcohol dehydrogenase", ignore_case = TRUE)))

```
