---
title: "5flye_1medaka"
author: "Krihs Desai"
format: html
editor: visual
---

# **Phase 1: Project Setup & Data Migration**

### **4. Load Libraries**

```{r}
#| echo: false
#| eval: false


#Loop that checks if the packages GO.db and AnnotationDbi are already installed
#If not, install them

p_check <- c("GO.db", "AnnotationDbi")

for(i in seq_along(p_check)){
  
  if(p_check[i] %in% installed.packages()[,"Package"]){
    print(paste("Package",p_check[i], "is already installed", sep = " "))
  }else{
    print(paste("installing package", p_check[i], sep = " ")) 
    BiocManager::install(p_check[i], force = TRUE)
  }
}
#Install the ggVennDiagram package
install.packages("ggVennDiagram")

```

```{r}
#| echo: false


#Load packages
library("tidyverse")
library("Gviz")
library("GenomicFeatures")
library("rtracklayer")
library("Biostrings")
library("GO.db")
library("AnnotationDbi")
library("ggVennDiagram")
```

# **Phase 2: Structural Visualization**

```{r}
#| echo: false


gff_path <- "data/data_Krish/Saccharomyces_cerevisiae.gff3"

txdb_demo <- makeTxDbFromGFF(gff_path, format = "gff3")

biostring_assembly <- Biostrings:: readDNAStringSet("data/data_Krish/assembly.fasta")


which(width(biostring_assembly) == max(width(biostring_assembly)))
biostring_assembly[209]

which(seqlevels(txdb_demo) == "scaffold_289")
seqlevels(txdb_demo)

options(ucscChromosomeNames=FALSE)

plot_track <- GeneRegionTrack(txdb_demo, 
                             chromosome = seqlevels(txdb_demo)[211],
                             name = "Predicted Genes",
                             transcriptAnnotation = "gene",
                             background.title = "darkgreen")
axis_track <- GenomeAxisTrack()
Scaffold_289 <- plotTracks(list(axis_track, plot_track),
           from = 1000, 
           to = 3500,
           chromosome = seqlevels(txdb_demo)[211],
           main = "Funannotate Predictions: Scaffold 289")

```

# **Phase 3: Integrating Function**

```{r}

annotations <- readxl::read_excel("data/data_Krish/5scaff1med.emapper.annotations.xlsx", skip = 2)


GRanges_gff <- import.gff3("data/data_Krish/Saccharomyces_cerevisiae.gff3")

GRanges_gff <- GRanges_gff[GRanges_gff$type == "mRNA"]


GRanges_match <- match(GRanges_gff$ID, annotations$query)
```
