---
title: "5scaff2medaka"
format: html
---

```{r}
#| echo: false
#Loop that checks if the packages GO.db and AnnotationDbi are already installed
#If not, install them

p_check <- c("GO.db", "AnnotationDbi")

for(i in seq_along(p_check)){
  
  if(p_check[i] %in% installed.packages()[,"Package"]){
    print(paste("Package",p_check[i], "is already installed", sep = " "))
  }else{
    print(paste("installing package", p_check[i], sep = " ")) 
    BiocManager::install(p_check[i], force = TRUE)
  }
}
```

```{r}
#| echo: false
#Install the ggVennDiagram package
install.packages("ggVennDiagram")
#Load packages
library("tidyverse")
library("Gviz")
library("GenomicFeatures")
library("rtracklayer")
library("Biostrings")
library("GO.db")
library("AnnotationDbi")
library("ggVennDiagram")
```

```{r}
gff_path <- "data/Ankur/Saccharomyces_cerevisiae.gff3"

txdb <- makeTxDbFromGFF(gff_path, format = "gff3")

txdb

biostring_assembly <- Biostrings::readDNAStringSet("data/Ankur/assembly.fasta")
which(width(biostring_assembly)==max(width(biostring_assembly)))
biostring_assembly[209]
which(seqlevels(txdb)=="scaffold_289")
seqlevels(txdb)

```

```{r}
options(ucscChromosomeNames=FALSE)

track <- GeneRegionTrack(txdb, 
                             chromosome = seqlevels(txdb)[211],
                             name = "Predicted Genes",
                             transcriptAnnotation = "gene",
                             background.title = "darkgreen")
```

```{r}
axis_track <- GenomeAxisTrack()

Scaffold_211 <- plotTracks(list(axis_track, track),
           from = 1, 
           to = 18000,
           chromosome = seqlevels(txdb)[211],
           main = "Funannotate Predictions: Scaffold 211")
```

```{r}
# ggsave("figures/Ankur/Scaffold_211.png", get_last_plot())
```

```{r}
library(readxl)
annotations <- read_excel("data/Ankur/5scaff2med.emapper.annotations.xlsx", skip = 2)

GRanges <- import.gff3("data/Ankur/Saccharomyces_cerevisiae.gff3")
GRanges
```

```{r}
GRanges <- GRanges[GRanges$type=="mRNA"]

symbol_to_attach <- match(GRanges$ID, annotations$query)

GRanges$symbol <-annotations$Preferred_name[symbol_to_attach]


GRanges$symbol[is.na(GRanges$symbol)] <- GRanges$ID[is.na(GRanges$symbol)]

```

```{r}
functional_track <- GeneRegionTrack(GRanges, 
                             chromosome = seqlevels(GRanges)[211],
                             name = "Predicted Genes - Functional Track",
                             transcriptAnnotation = "symbol",
                             background.title = "darkgreen")

axis_track <- GenomeAxisTrack()

# track_functional <- plotTracks(list(axis_track, GRanges),
  #         from = 7000, 
   #        to = 18000,
    #       chromosome = seqlevels(GRanges)[211],
     #      main = "Funannotate Predictions: Scaffold 211")
```

```{r}
annotations_eggnog_km <- readxl::read_excel("data/Ankur/5scaff2med.emapper.annotations.xlsx", skip = 2)

GRanges_gff <- import.gff("data/Ankur/Saccharomyces_cerevisiae.gff3")

match_gff_eggnog <- match(GRanges_gff$ID, annotations_eggnog_km$query)

GRanges_gff$symbol <- annotations_eggnog_km$Preferred_name[match_gff_eggnog]

GRanges_gff$symbol


options(ucscChromosomeNames=FALSE)
fung_track <- GeneRegionTrack(GRanges_gff, 
                             chromosome = seqlevels(GRanges_gff)[211],
                             name = "Predicted Genes",
                             transcriptAnnotation = "symbol",
                             background.title = "darkgreen")
axis_track <- GenomeAxisTrack()

plot_matches <- plotTracks(list(axis_track, fung_track),
           from = 1, 
           to = 18000,
           chromosome = seqlevels(GRanges_gff)[211],
           main = "Funannotate Predictions: Matches")
```

```{r}
#Convert to long table
annotations_long <- annotations %>%
  separate_rows(GOs, sep = ",")

#Get the terms and the ontology
annotations_long$TERM <- AnnotationDbi::select(GO.db,
                                      keys = annotations_long$GOs,
                                      columns = c("TERM"),
                                      keytype = "GOID")$TERM

GO_TERM <- AnnotationDbi::select(GO.db,
                                      keys = unique(annotations_long$GOs),
                                      columns = c("TERM"),
                                      keytype = "GOID")


annotations_long <- left_join(annotations_long, GO_TERM, by = c("GOs"="GOID"))
                              
```

```{r}
Top_10_terms <- annotations_long |>
  count(TERM, sort = TRUE) |>
  filter(!is.na(TERM)) |> 
  slice_head(n=25)
```

```{r}
ggplot(Top_10_terms, aes(x = reorder(TERM, n), y = n)) +
  geom_col() + 
  coord_flip() +  # Makes long labels readable
  labs(x = "GO Term", y = "Count")
```

```{r}
# Example search terms: "glycolysis", "fermentation"
pathway_hits <- annotations %>%
  filter(str_detect(Description, regex("alcohol", ignore_case = TRUE)))

# Example search terms: "glycolysis", "fermentation"
pathway_hits2 <- annotations %>%
  filter(str_detect(Description, regex("adh", ignore_case = TRUE)))
```

```{r}
list_of_annotation_data <- list(
  alcohol = pathway_hits,
  adh = pathway_hits2
)

sets <- lapply(list_of_annotation_data, function(df) {
  df$Preferred_name[df$Preferred_name != "-"]
})

names(sets) <- names(list_of_annotation_data)

ggVennDiagram(sets)


```
